language: python

dist: trusty

branches:
  only:
    - /.*/

sudo: false

addons:
  apt:
    packages:
      - libwww-perl
      - libcss-dom-perl
  chrome: stable

cache:
  directories:
    - node_modules # NPM packages

before_install:
  - nvm install lts/*

install:
 - make travissetup

script:
 - make check

env:
  global:
    - URL="https://w3c.github.io/mediacapture-output/W3CTRMANIFEST"
    - DECISION="https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0031.html"
    - secure: "IxbwoPaIvdMg2LhW484WL3cYoXNujggRF/gQnQt2RVvvB6RrLXqC1AKv9rHIQ5hzsCO+c0hjEA/TBGJ1OWPbyMZ6ZitEUdj6AfCIVIpKVWYg0yvephWbsUxAyVdeUKxuTnilW/AsewZt94jAfhSWwf0Dy4t5qA0SsJV+TO/uURc="

after_success:
  - test $TRAVIS_BRANCH = "gh-pages" -a $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
